import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Basir',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'John',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
    products: [
    // 👕 Shirts
    {
      name: 'Nike Slim Shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/shirts/nike1.jpg',
      price: 120,
      countInStock: 12,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'High-quality cotton slim shirt for men.',
    },
    {
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/shirts/adidas1.jpg',
      price: 95,
      countInStock: 7,
      brand: 'Adidas',
      rating: 4.2,
      numReviews: 8,
      description: 'Lightweight and breathable fit shirt.',
    },
    // 👖 Pants
    {
      name: 'Levi’s 511 Slim Fit Jeans',
      slug: 'levis-511-jeans',
      category: 'Pants',
      image: '/images/pants/levis1.jpg',
      price: 70,
      countInStock: 15,
      brand: 'Levi’s',
      rating: 4.6,
      numReviews: 12,
      description: 'Classic denim jeans with a modern slim fit.',
    },
    {
      name: 'Zara Chino Pants',
      slug: 'zara-chino-pants',
      category: 'Pants',
      image: '/images/pants/zara1.jpg',
      price: 55,
      countInStock: 10,
      brand: 'Zara',
      rating: 4.3,
      numReviews: 6,
      description: 'Casual chinos perfect for daily wear.',
    },
    // 👟 Shoes
    {
      name: 'Nike Air Zoom Pegasus',
      slug: 'nike-air-pegasus',
      category: 'Shoes',
      image: '/images/shoes/nike1.jpg',
      price: 150,
      countInStock: 20,
      brand: 'Nike',
      rating: 4.8,
      numReviews: 40,
      description: 'Comfortable running shoes with responsive cushioning.',
    },
    {
      name: 'Converse Chuck Taylor',
      slug: 'converse-chuck-taylor',
      category: 'Shoes',
      image: '/images/shoes/converse1.jpg',
      price: 75,
      countInStock: 25,
      brand: 'Converse',
      rating: 4.7,
      numReviews: 32,
      description: 'Classic canvas sneakers that never go out of style.',
    },
    // ⌚ Watches
    {
      name: 'Fossil Chronograph Watch',
      slug: 'fossil-chronograph',
      category: 'Watches',
      image: '/images/watches/fossil1.jpg',
      price: 220,
      countInStock: 8,
      brand: 'Fossil',
      rating: 4.5,
      numReviews: 18,
      description: 'Stylish stainless steel chronograph watch.',
    },
    {
      name: 'Apple Watch Series 9',
      slug: 'apple-watch-series9',
      category: 'Watches',
      image: '/images/watches/apple9.jpg',
      price: 499,
      countInStock: 5,
      brand: 'Apple',
      rating: 4.9,
      numReviews: 55,
      description: 'Latest Apple Watch with advanced health tracking features.',
    },
    // 📱 Electronics
    {
      name: 'Samsung Galaxy S24',
      slug: 'samsung-galaxy-s24',
      category: 'Electronics',
      image: '/images/electronics/s24.jpg',
      price: 899,
      countInStock: 9,
      brand: 'Samsung',
      rating: 4.8,
      numReviews: 45,
      description: 'Powerful smartphone with exceptional camera performance.',
    },
    {
      name: 'Sony WH-1000XM5 Headphones',
      slug: 'sony-wh1000xm5',
      category: 'Electronics',
      image: '/images/electronics/sony1.jpg',
      price: 399,
      countInStock: 18,
      brand: 'Sony',
      rating: 4.9,
      numReviews: 70,
      description: 'Top-tier noise-cancelling wireless headphones.',
    },
    // 🛋️ Furniture
    {
      name: 'IKEA Modern Sofa',
      slug: 'ikea-modern-sofa',
      category: 'Furniture',
      image: '/images/furniture/sofa1.jpg',
      price: 650,
      countInStock: 3,
      brand: 'IKEA',
      rating: 4.4,
      numReviews: 20,
      description: 'Comfortable 3-seater sofa with minimal design.',
    },
    {
      name: 'Wooden Dining Table Set',
      slug: 'wooden-dining-table',
      category: 'Furniture',
      image: '/images/furniture/table1.jpg',
      price: 980,
      countInStock: 2,
      brand: 'HomeCraft',
      rating: 4.6,
      numReviews: 15,
      description: 'Solid wood table with six comfortable chairs.',
    },
    // 💄 Beauty
    {
      name: 'L’Oréal Revitalift Cream',
      slug: 'loreal-revitalift',
      category: 'Beauty',
      image: '/images/beauty/loreal1.jpg',
      price: 45,
      countInStock: 30,
      brand: 'L’Oréal',
      rating: 4.3,
      numReviews: 25,
      description: 'Anti-aging cream for smooth and radiant skin.',
    },
    {
      name: 'Maybelline Mascara',
      slug: 'maybelline-mascara',
      category: 'Beauty',
      image: '/images/beauty/maybelline1.jpg',
      price: 20,
      countInStock: 40,
      brand: 'Maybelline',
      rating: 4.5,
      numReviews: 30,
      description: 'Long-lasting waterproof mascara for all-day wear.',
    },
    // 📚 Books
    {
      name: 'Atomic Habits',
      slug: 'atomic-habits',
      category: 'Books',
      image: '/images/books/atomic-habits.jpg',
      price: 15,
      countInStock: 50,
      brand: 'Penguin',
      rating: 4.9,
      numReviews: 200,
      description: 'An easy & proven way to build good habits and break bad ones.',
    },
    {
      name: 'The Alchemist',
      slug: 'the-alchemist',
      category: 'Books',
      image: '/images/books/alchemist.jpg',
      price: 12,
      countInStock: 60,
      brand: 'HarperOne',
      rating: 4.8,
      numReviews: 180,
      description: 'A journey of self-discovery by Paulo Coelho.',
    },
    // 🥫 Groceries
    {
      name: 'Organic Honey 500g',
      slug: 'organic-honey',
      category: 'Groceries',
      image: '/images/groceries/honey.jpg',
      price: 10,
      countInStock: 100,
      brand: 'Nature’s Best',
      rating: 4.7,
      numReviews: 35,
      description: 'Pure organic honey sourced from wild forests.',
    },
    {
      name: 'Arabica Coffee Beans 1kg',
      slug: 'arabica-coffee',
      category: 'Groceries',
      image: '/images/groceries/coffee.jpg',
      price: 18,
      countInStock: 40,
      brand: 'CoffeeCo',
      rating: 4.6,
      numReviews: 22,
      description: 'Premium 100% Arabica beans for rich flavor.',
    },
    // 🏋️ Sports
    {
      name: 'Yoga Mat Pro',
      slug: 'yoga-mat-pro',
      category: 'Sports',
      image: '/images/sports/yogamat.jpg',
      price: 35,
      countInStock: 25,
      brand: 'FitLife',
      rating: 4.4,
      numReviews: 14,
      description: 'Eco-friendly, non-slip yoga mat.',
    },
    {
      name: 'Adidas Football',
      slug: 'adidas-football',
      category: 'Sports',
      image: '/images/sports/football.jpg',
      price: 40,
      countInStock: 30,
      brand: 'Adidas',
      rating: 4.7,
      numReviews: 19,
      description: 'Durable and official size football for training.',
    }
],
  };
  export default data;